#%RAML 1.0
title: Deloitte Order API
version: v1
baseUri: http://myhost/assignment/{version}

uses:
  entity: entity.schema.raml

resourceTypes:
  collection:
    get:
      is:  [paging]
      description: Get list of <<resourcePathName>>
      responses:
        200:
          body:
            application/json:
              type: <<entityType>>[]
              example: <<exampleList>>[]

    post:
      description: Create a new <<resourcePathName|!singularize>>
      body:
        application/json:         
          example: <<exampleNewEntity>>        
      responses:
        201:
          body:
            application/json:


  collection-item:
    get:
      description: Get details of a single <<resourcePathName|!singularize>> for the given id
      responses:
        200:
          body:
            application/json:             
              example: <<exampleEntity>>
        404:
          description: <<resourcePathName|!singularize>> not found for given id

    put:
      description: Update details of a single <<resourcePathName|!singularize>> for the given id
      body:
        application/json:        
          example: <<exampleEntity>>
      responses:
        204:
          description: <<resourcePathName|!singularize>> successfully updated.
        404:
          description: <<resourcePathName|!singularize>> not found for given id


    delete:
      description: Delete <<resourcePathName|!singularize>> for the given id
      responses:
        204:
          description: <<resourcePathName|!singularize>> successfully deleted.
        404:
          description: <<resourcePathName|!singularize>> not found for given id

traits:
  paging:
    queryParameters:
      size:
        description: Page size
        type: integer
        required: false
        example: 10
      page:
        description: Page number
        type: integer
        required: false
        example: 3

/orders:
  type:
     collection:
        entityType : entity.Order
        exampleNewEntity: !newOrder-sample.json
        exampleList: !listOrders-sample.json

  /{id}:
    type:  
      collection-item: 
        entityType : entity.Order
        exampleEntity: !getOrder-sample.json
